# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8"
    chainName: anvil2
    connections:
      - token: ethereum|anvil1|0x998abeb3E57409262aE5b751f60747921B33613E
    decimals: 6
    name: USDT
    standard: EvmHypSynthetic
    symbol: USDT
  - addressOrDenom: "0x998abeb3E57409262aE5b751f60747921B33613E"
    chainName: anvil1
    collateralAddressOrDenom: "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8"
    connections:
      - token: ethereum|anvil2|0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8
    decimals: 6
    name: USDT
    standard: EvmHypCollateral
    symbol: USDT
