# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x4ed7c70F96B99c776995fB64377f0d4aB3B0e1C1"
    chainName: anvil2
    connections:
      - token: ethereum|anvil1|0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f
    decimals: 6
    name: USDC
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f"
    chainName: anvil1
    collateralAddressOrDenom: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
    connections:
      - token: ethereum|anvil2|0x4ed7c70F96B99c776995fB64377f0d4aB3B0e1C1
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
