# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xDFd503312a1f6E3853a15ba0C76F5AFA4DE1a60e"
    chainName: sepolia
    decimals: 6
    name: USDC
    standard: EvmHypSynthetic
    symbol: USDC
