# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x3Be329Ce05442c6B4b055C68141b2bCa568223C0"
    chainName: sepolia
    decimals: 6
    name: USDC
    standard: EvmHypSynthetic
    symbol: USDC
